workflows:
  android-release:
    name: 人生五册 APK
    environment:
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
